spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rental_cloud?createDatabaseIfNotExist=true
    username: root
    password: Admin
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9090/oauth/check_token
    client:
      client-id: mobile
      client-secret: pass